class Failure {
  final String message;
  const Failure([this.message = 'An Unexpected error has occurred']);
}
